#!/usr/bin/env python3
"""Regenerate the vendored community node-types.json byproducts (V5/V6).

Checks (and optionally rewrites) the five retained community fixtures so the
committed `node-types.json` files are exactly the installed tree-sitter
CLI's byproduct — byte for byte, no JSON normalization, no shelling out to a
mock. The claim is: the tracked file == what `tree-sitter generate` writes
for the committed grammar source with the supported CLI.

Usage (from the repository root, through the managed shell):

    # Check only; no repository mutation. Exits 1 if any fixture differs.
    devenv shell -- python tests/regenerate_community_node_types.py

    # Intentional refresh after inspecting upstream/toolchain changes.
    devenv shell -- python tests/regenerate_community_node_types.py --write

An optional repeated fixture selector limits the run to the named fixture
directories (default: all five in the manifest):

    devenv shell -- python tests/regenerate_community_node_types.py bash nix

The write path uses atomic replacement (temp file + os.replace) and never
touches the grammar source files — only the expected byproduct.
"""

from __future__ import annotations

import argparse
import difflib
import os
import subprocess
import sys
import tempfile
from pathlib import Path

from community_fixture_manifest import COMMUNITY_FIXTURES, CommunityFixture

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURES = REPO_ROOT / "tests" / "fixtures"


def cli_version() -> str:
    """The installed tree-sitter CLI version string ('' when absent)."""
    try:
        out = subprocess.run(["tree-sitter", "--version"],
                             capture_output=True, text=True)
        return (out.stdout or out.stderr).strip()
    except FileNotFoundError:
        return "(tree-sitter not on PATH)"


def generate_byproduct(fixture: CommunityFixture, tmp: Path) -> bytes:
    """Run derive_schema_for_dir over the committed source dir and return the
    generated byproduct bytes (the CLI's own node-types.json)."""
    from pydantree_sitter_grammar.schema_tool import derive_schema_for_dir

    src = FIXTURES / fixture.dir_name
    out = tmp / "node-schema.json"
    derive_schema_for_dir(src, name=fixture.grammar_name,
                          workdir=tmp / "cw", out=out, keep=True)
    raw = (tmp / "cw" / "gen" / "node-types.json").read_bytes()
    # the schema serialization is the CLI byproduct (D3) — assert it here so
    # a pydantic serialization change can never masquerade as CLI output.
    if out.read_bytes() != raw:
        raise RuntimeError(
            f"{fixture.dir_name}: schema serialization drifted from the raw "
            f"CLI byproduct — investigate before refreshing")
    return raw


def unified_diff_bytes(name: str, tracked: bytes, fresh: bytes) -> str:
    return "\n".join(difflib.unified_diff(
        tracked.decode(errors="replace").splitlines(),
        fresh.decode(errors="replace").splitlines(),
        fromfile=f"{name}/node-types.json (tracked)",
        tofile=f"{name}/node-types.json (fresh CLI byproduct)",
        lineterm=""))


def check_one(fixture: CommunityFixture, tmp: Path) -> tuple[bytes, bytes]:
    """Return (tracked, fresh) bytes for one fixture."""
    tracked = (FIXTURES / fixture.dir_name / fixture.byproduct_path).read_bytes()
    fresh = generate_byproduct(fixture, tmp)
    return tracked, fresh


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("selectors", nargs="*",
                        help="fixture dir names to check/write (default: all)")
    parser.add_argument("--write", action="store_true",
                        help="replace tracked fixtures that differ (atomic)")
    args = parser.parse_args(argv)

    selectors = set(args.selectors)
    fixtures = [f for f in COMMUNITY_FIXTURES
                if not selectors or f.dir_name in selectors]
    if not fixtures:
        parser.error(f"no manifest fixture matches {sorted(selectors)}")
    missing = selectors - {f.dir_name for f in COMMUNITY_FIXTURES}
    if missing:
        parser.error(f"unknown fixture selector(s): {sorted(missing)}")

    print(f"tree-sitter CLI: {cli_version()}")
    print(f"supported CLI range: 0.25.x (pinned 0.25.3 in this repository)")
    print(f"mode: {'WRITE (atomic replacement)' if args.write else 'check only'}")
    print()

    changed, unchanged = [], []
    rc = 0
    with tempfile.TemporaryDirectory(prefix="pydantree-node-types-") as td:
        tmp = Path(td)
        for fixture in fixtures:
            tracked, fresh = check_one(fixture, tmp)
            target = FIXTURES / fixture.dir_name / fixture.byproduct_path
            if tracked == fresh:
                unchanged.append(fixture.dir_name)
                print(f"  {fixture.dir_name}/{fixture.byproduct_path}: unchanged")
                continue
            rc = 1
            print(f"  {fixture.dir_name}/{fixture.byproduct_path}: DIFFERS")
            print(unified_diff_bytes(fixture.dir_name, tracked, fresh))
            if args.write:
                # atomic replacement: temp file in the same dir, then rename
                fd, tmp_path = tempfile.mkstemp(
                    dir=str(target.parent), prefix=".node-types-", suffix=".tmp")
                try:
                    with os.fdopen(fd, "wb") as fh:
                        fh.write(fresh)
                    os.replace(tmp_path, target)
                except BaseException:
                    try:
                        os.unlink(tmp_path)
                    except FileNotFoundError:
                        pass
                    raise
                changed.append(fixture.dir_name)
                print(f"    -> replaced {target}")
            else:
                changed.append(fixture.dir_name)
                print(f"    -> run with --write to replace the tracked file")

    print()
    if changed:
        print(f"{len(changed)} fixture(s) differ: {', '.join(changed)}")
    if unchanged:
        print(f"{len(unchanged)} fixture(s) unchanged: {', '.join(unchanged)}")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
