# Typed node accessors for bash — generated from the node-schema (tsquery.stubs).
from __future__ import annotations
from typing import Literal, overload

class Node:
    type: str
    ...

_expression = _primary_expression | binary_expression | concatenation | parenthesized_expression | postfix_expression | ternary_expression | unary_expression | word

_primary_expression = ansi_c_string | arithmetic_expansion | brace_expression | command_substitution | expansion | number | process_substitution | raw_string | simple_expansion | string | translated_string | word

_statement = c_style_for_statement | case_statement | command | compound_statement | declaration_command | for_statement | function_definition | if_statement | list | negated_command | pipeline | redirected_statement | subshell | test_command | unset_command | variable_assignment | variable_assignments | while_statement

class ansi_c_string(Node):
    """kind 'ansi_c_string'."""
    ...

class arithmetic_expansion(Node):
    """kind 'arithmetic_expansion'."""
    @overload
    def children(self, kind: Literal['binary_expression']) -> list[binary_expression]: ...
    @overload
    def children(self, kind: Literal['command_substitution']) -> list[command_substitution]: ...
    @overload
    def children(self, kind: Literal['expansion']) -> list[expansion]: ...
    @overload
    def children(self, kind: Literal['number']) -> list[number]: ...
    @overload
    def children(self, kind: Literal['parenthesized_expression']) -> list[parenthesized_expression]: ...
    @overload
    def children(self, kind: Literal['postfix_expression']) -> list[postfix_expression]: ...
    @overload
    def children(self, kind: Literal['raw_string']) -> list[raw_string]: ...
    @overload
    def children(self, kind: Literal['simple_expansion']) -> list[simple_expansion]: ...
    @overload
    def children(self, kind: Literal['string']) -> list[string]: ...
    @overload
    def children(self, kind: Literal['subscript']) -> list[subscript]: ...
    @overload
    def children(self, kind: Literal['ternary_expression']) -> list[ternary_expression]: ...
    @overload
    def children(self, kind: Literal['unary_expression']) -> list[unary_expression]: ...
    @overload
    def children(self, kind: Literal['variable_name']) -> list[variable_name]: ...

class array(Node):
    """kind 'array'."""
    @overload
    def children(self, kind: Literal['_primary_expression']) -> list[_primary_expression]: ...
    @overload
    def children(self, kind: Literal['concatenation']) -> list[concatenation]: ...

class binary_expression(Node):
    """kind 'binary_expression'."""
    def left(self) -> _expression | command_substitution | expansion | number | raw_string | simple_expansion | string | subscript | variable_name | None: ...
    def operator(self) -> Node | test_operator | None: ...
    def right(self) -> list[_expression | command_substitution | expansion | extglob_pattern | number | raw_string | regex | simple_expansion | string | subscript | variable_name]: ...
    @overload
    def get(self, field: Literal['left']) -> _expression | command_substitution | expansion | number | raw_string | simple_expansion | string | subscript | variable_name | None: ...
    @overload
    def get(self, field: Literal['operator']) -> Node | test_operator | None: ...
    @overload
    def get(self, field: Literal['right']) -> list[_expression | command_substitution | expansion | extglob_pattern | number | raw_string | regex | simple_expansion | string | subscript | variable_name]: ...
    @overload
    def children(self, kind: Literal['binary_expression']) -> list[binary_expression]: ...
    @overload
    def children(self, kind: Literal['expansion']) -> list[expansion]: ...
    @overload
    def children(self, kind: Literal['number']) -> list[number]: ...
    @overload
    def children(self, kind: Literal['variable_name']) -> list[variable_name]: ...

class brace_expression(Node):
    """kind 'brace_expression'."""
    def children(self, kind: Literal['number']) -> list[number]: ...

class c_style_for_statement(Node):
    """kind 'c_style_for_statement'."""
    def body(self) -> compound_statement | do_group | None: ...
    def condition(self) -> list[Node | binary_expression | command_substitution | expansion | number | parenthesized_expression | postfix_expression | simple_expansion | string | unary_expression | variable_assignment | word]: ...
    def initializer(self) -> list[Node | binary_expression | command_substitution | expansion | number | parenthesized_expression | postfix_expression | simple_expansion | string | unary_expression | variable_assignment | word]: ...
    def update(self) -> list[Node | binary_expression | command_substitution | expansion | number | parenthesized_expression | postfix_expression | simple_expansion | string | unary_expression | variable_assignment | word]: ...
    @overload
    def get(self, field: Literal['body']) -> compound_statement | do_group | None: ...
    @overload
    def get(self, field: Literal['condition']) -> list[Node | binary_expression | command_substitution | expansion | number | parenthesized_expression | postfix_expression | simple_expansion | string | unary_expression | variable_assignment | word]: ...
    @overload
    def get(self, field: Literal['initializer']) -> list[Node | binary_expression | command_substitution | expansion | number | parenthesized_expression | postfix_expression | simple_expansion | string | unary_expression | variable_assignment | word]: ...
    @overload
    def get(self, field: Literal['update']) -> list[Node | binary_expression | command_substitution | expansion | number | parenthesized_expression | postfix_expression | simple_expansion | string | unary_expression | variable_assignment | word]: ...

class case_item(Node):
    """kind 'case_item'."""
    def fallthrough(self) -> Node | None: ...
    def termination(self) -> Node | None: ...
    def value(self) -> list[_primary_expression | concatenation | extglob_pattern]: ...
    @overload
    def get(self, field: Literal['fallthrough']) -> Node | None: ...
    @overload
    def get(self, field: Literal['termination']) -> Node | None: ...
    @overload
    def get(self, field: Literal['value']) -> list[_primary_expression | concatenation | extglob_pattern]: ...
    def children(self, kind: Literal['_statement']) -> list[_statement]: ...

class case_statement(Node):
    """kind 'case_statement'."""
    def value(self) -> _primary_expression | concatenation | None: ...
    def get(self, field: Literal['value']) -> _primary_expression | concatenation | None: ...
    def children(self, kind: Literal['case_item']) -> list[case_item]: ...

class command(Node):
    """kind 'command'."""
    def argument(self) -> list[Node | _primary_expression | concatenation | regex]: ...
    def name(self) -> command_name | None: ...
    def redirect(self) -> list[file_redirect | herestring_redirect]: ...
    @overload
    def get(self, field: Literal['argument']) -> list[Node | _primary_expression | concatenation | regex]: ...
    @overload
    def get(self, field: Literal['name']) -> command_name | None: ...
    @overload
    def get(self, field: Literal['redirect']) -> list[file_redirect | herestring_redirect]: ...
    @overload
    def children(self, kind: Literal['subshell']) -> list[subshell]: ...
    @overload
    def children(self, kind: Literal['variable_assignment']) -> list[variable_assignment]: ...

class command_name(Node):
    """kind 'command_name'."""
    @overload
    def children(self, kind: Literal['_primary_expression']) -> list[_primary_expression]: ...
    @overload
    def children(self, kind: Literal['concatenation']) -> list[concatenation]: ...

class command_substitution(Node):
    """kind 'command_substitution'."""
    def redirect(self) -> file_redirect | None: ...
    def get(self, field: Literal['redirect']) -> file_redirect | None: ...
    def children(self, kind: Literal['_statement']) -> list[_statement]: ...

class comment(Node):
    """kind 'comment'."""
    ...

class compound_statement(Node):
    """kind 'compound_statement'."""
    @overload
    def children(self, kind: Literal['_statement']) -> list[_statement]: ...
    @overload
    def children(self, kind: Literal['binary_expression']) -> list[binary_expression]: ...
    @overload
    def children(self, kind: Literal['command_substitution']) -> list[command_substitution]: ...
    @overload
    def children(self, kind: Literal['expansion']) -> list[expansion]: ...
    @overload
    def children(self, kind: Literal['number']) -> list[number]: ...
    @overload
    def children(self, kind: Literal['parenthesized_expression']) -> list[parenthesized_expression]: ...
    @overload
    def children(self, kind: Literal['postfix_expression']) -> list[postfix_expression]: ...
    @overload
    def children(self, kind: Literal['raw_string']) -> list[raw_string]: ...
    @overload
    def children(self, kind: Literal['simple_expansion']) -> list[simple_expansion]: ...
    @overload
    def children(self, kind: Literal['string']) -> list[string]: ...
    @overload
    def children(self, kind: Literal['subscript']) -> list[subscript]: ...
    @overload
    def children(self, kind: Literal['ternary_expression']) -> list[ternary_expression]: ...
    @overload
    def children(self, kind: Literal['unary_expression']) -> list[unary_expression]: ...
    @overload
    def children(self, kind: Literal['variable_name']) -> list[variable_name]: ...

class concatenation(Node):
    """kind 'concatenation'."""
    @overload
    def children(self, kind: Literal['_primary_expression']) -> list[_primary_expression]: ...
    @overload
    def children(self, kind: Literal['array']) -> list[array]: ...
    @overload
    def children(self, kind: Literal['variable_name']) -> list[variable_name]: ...

class declaration_command(Node):
    """kind 'declaration_command'."""
    @overload
    def children(self, kind: Literal['_primary_expression']) -> list[_primary_expression]: ...
    @overload
    def children(self, kind: Literal['concatenation']) -> list[concatenation]: ...
    @overload
    def children(self, kind: Literal['variable_assignment']) -> list[variable_assignment]: ...
    @overload
    def children(self, kind: Literal['variable_name']) -> list[variable_name]: ...

class do_group(Node):
    """kind 'do_group'."""
    def children(self, kind: Literal['_statement']) -> list[_statement]: ...

class elif_clause(Node):
    """kind 'elif_clause'."""
    def children(self, kind: Literal['_statement']) -> list[_statement]: ...

class else_clause(Node):
    """kind 'else_clause'."""
    def children(self, kind: Literal['_statement']) -> list[_statement]: ...

class expansion(Node):
    """kind 'expansion'."""
    def operator(self) -> list[Node]: ...
    def get(self, field: Literal['operator']) -> list[Node]: ...
    @overload
    def children(self, kind: Literal['_primary_expression']) -> list[_primary_expression]: ...
    @overload
    def children(self, kind: Literal['array']) -> list[array]: ...
    @overload
    def children(self, kind: Literal['binary_expression']) -> list[binary_expression]: ...
    @overload
    def children(self, kind: Literal['concatenation']) -> list[concatenation]: ...
    @overload
    def children(self, kind: Literal['parenthesized_expression']) -> list[parenthesized_expression]: ...
    @overload
    def children(self, kind: Literal['regex']) -> list[regex]: ...
    @overload
    def children(self, kind: Literal['special_variable_name']) -> list[special_variable_name]: ...
    @overload
    def children(self, kind: Literal['subscript']) -> list[subscript]: ...
    @overload
    def children(self, kind: Literal['variable_name']) -> list[variable_name]: ...

class extglob_pattern(Node):
    """kind 'extglob_pattern'."""
    ...

class file_descriptor(Node):
    """kind 'file_descriptor'."""
    ...

class file_redirect(Node):
    """kind 'file_redirect'."""
    def descriptor(self) -> file_descriptor | None: ...
    def destination(self) -> list[_primary_expression | concatenation]: ...
    @overload
    def get(self, field: Literal['descriptor']) -> file_descriptor | None: ...
    @overload
    def get(self, field: Literal['destination']) -> list[_primary_expression | concatenation]: ...

class for_statement(Node):
    """kind 'for_statement'."""
    def body(self) -> do_group | None: ...
    def value(self) -> list[_primary_expression | concatenation]: ...
    def variable(self) -> variable_name | None: ...
    @overload
    def get(self, field: Literal['body']) -> do_group | None: ...
    @overload
    def get(self, field: Literal['value']) -> list[_primary_expression | concatenation]: ...
    @overload
    def get(self, field: Literal['variable']) -> variable_name | None: ...

class function_definition(Node):
    """kind 'function_definition'."""
    def body(self) -> compound_statement | if_statement | subshell | test_command | None: ...
    def name(self) -> word | None: ...
    def redirect(self) -> file_redirect | herestring_redirect | None: ...
    @overload
    def get(self, field: Literal['body']) -> compound_statement | if_statement | subshell | test_command | None: ...
    @overload
    def get(self, field: Literal['name']) -> word | None: ...
    @overload
    def get(self, field: Literal['redirect']) -> file_redirect | herestring_redirect | None: ...

class heredoc_body(Node):
    """kind 'heredoc_body'."""
    @overload
    def children(self, kind: Literal['command_substitution']) -> list[command_substitution]: ...
    @overload
    def children(self, kind: Literal['expansion']) -> list[expansion]: ...
    @overload
    def children(self, kind: Literal['heredoc_content']) -> list[heredoc_content]: ...
    @overload
    def children(self, kind: Literal['simple_expansion']) -> list[simple_expansion]: ...

class heredoc_content(Node):
    """kind 'heredoc_content'."""
    ...

class heredoc_end(Node):
    """kind 'heredoc_end'."""
    ...

class heredoc_redirect(Node):
    """kind 'heredoc_redirect'."""
    def argument(self) -> list[_primary_expression | concatenation]: ...
    def descriptor(self) -> file_descriptor | None: ...
    def operator(self) -> Node | None: ...
    def redirect(self) -> list[file_redirect | herestring_redirect]: ...
    def right(self) -> _statement | None: ...
    @overload
    def get(self, field: Literal['argument']) -> list[_primary_expression | concatenation]: ...
    @overload
    def get(self, field: Literal['descriptor']) -> file_descriptor | None: ...
    @overload
    def get(self, field: Literal['operator']) -> Node | None: ...
    @overload
    def get(self, field: Literal['redirect']) -> list[file_redirect | herestring_redirect]: ...
    @overload
    def get(self, field: Literal['right']) -> _statement | None: ...
    @overload
    def children(self, kind: Literal['heredoc_body']) -> list[heredoc_body]: ...
    @overload
    def children(self, kind: Literal['heredoc_end']) -> list[heredoc_end]: ...
    @overload
    def children(self, kind: Literal['heredoc_start']) -> list[heredoc_start]: ...
    @overload
    def children(self, kind: Literal['pipeline']) -> list[pipeline]: ...

class heredoc_start(Node):
    """kind 'heredoc_start'."""
    ...

class herestring_redirect(Node):
    """kind 'herestring_redirect'."""
    def descriptor(self) -> file_descriptor | None: ...
    def get(self, field: Literal['descriptor']) -> file_descriptor | None: ...
    @overload
    def children(self, kind: Literal['_primary_expression']) -> list[_primary_expression]: ...
    @overload
    def children(self, kind: Literal['concatenation']) -> list[concatenation]: ...

class if_statement(Node):
    """kind 'if_statement'."""
    def condition(self) -> list[Node | _statement]: ...
    def get(self, field: Literal['condition']) -> list[Node | _statement]: ...
    @overload
    def children(self, kind: Literal['_statement']) -> list[_statement]: ...
    @overload
    def children(self, kind: Literal['elif_clause']) -> list[elif_clause]: ...
    @overload
    def children(self, kind: Literal['else_clause']) -> list[else_clause]: ...

class list(Node):
    """kind 'list'."""
    def children(self, kind: Literal['_statement']) -> list[_statement]: ...

class negated_command(Node):
    """kind 'negated_command'."""
    @overload
    def children(self, kind: Literal['command']) -> list[command]: ...
    @overload
    def children(self, kind: Literal['subshell']) -> list[subshell]: ...
    @overload
    def children(self, kind: Literal['test_command']) -> list[test_command]: ...
    @overload
    def children(self, kind: Literal['variable_assignment']) -> list[variable_assignment]: ...

class number(Node):
    """kind 'number'."""
    @overload
    def children(self, kind: Literal['command_substitution']) -> list[command_substitution]: ...
    @overload
    def children(self, kind: Literal['expansion']) -> list[expansion]: ...

class parenthesized_expression(Node):
    """kind 'parenthesized_expression'."""
    @overload
    def children(self, kind: Literal['_expression']) -> list[_expression]: ...
    @overload
    def children(self, kind: Literal['command_substitution']) -> list[command_substitution]: ...
    @overload
    def children(self, kind: Literal['expansion']) -> list[expansion]: ...
    @overload
    def children(self, kind: Literal['number']) -> list[number]: ...
    @overload
    def children(self, kind: Literal['raw_string']) -> list[raw_string]: ...
    @overload
    def children(self, kind: Literal['simple_expansion']) -> list[simple_expansion]: ...
    @overload
    def children(self, kind: Literal['string']) -> list[string]: ...
    @overload
    def children(self, kind: Literal['subscript']) -> list[subscript]: ...
    @overload
    def children(self, kind: Literal['variable_assignment']) -> list[variable_assignment]: ...
    @overload
    def children(self, kind: Literal['variable_name']) -> list[variable_name]: ...

class pipeline(Node):
    """kind 'pipeline'."""
    def children(self, kind: Literal['_statement']) -> list[_statement]: ...

class postfix_expression(Node):
    """kind 'postfix_expression'."""
    def operator(self) -> Node | None: ...
    def get(self, field: Literal['operator']) -> Node | None: ...
    @overload
    def children(self, kind: Literal['_expression']) -> list[_expression]: ...
    @overload
    def children(self, kind: Literal['command_substitution']) -> list[command_substitution]: ...
    @overload
    def children(self, kind: Literal['expansion']) -> list[expansion]: ...
    @overload
    def children(self, kind: Literal['number']) -> list[number]: ...
    @overload
    def children(self, kind: Literal['raw_string']) -> list[raw_string]: ...
    @overload
    def children(self, kind: Literal['simple_expansion']) -> list[simple_expansion]: ...
    @overload
    def children(self, kind: Literal['string']) -> list[string]: ...
    @overload
    def children(self, kind: Literal['subscript']) -> list[subscript]: ...
    @overload
    def children(self, kind: Literal['variable_name']) -> list[variable_name]: ...

class process_substitution(Node):
    """kind 'process_substitution'."""
    def children(self, kind: Literal['_statement']) -> list[_statement]: ...

class program(Node):
    """kind 'program'."""
    def children(self, kind: Literal['_statement']) -> list[_statement]: ...

class raw_string(Node):
    """kind 'raw_string'."""
    ...

class redirected_statement(Node):
    """kind 'redirected_statement'."""
    def body(self) -> _statement | None: ...
    def redirect(self) -> list[file_redirect | heredoc_redirect | herestring_redirect]: ...
    @overload
    def get(self, field: Literal['body']) -> _statement | None: ...
    @overload
    def get(self, field: Literal['redirect']) -> list[file_redirect | heredoc_redirect | herestring_redirect]: ...
    def children(self, kind: Literal['herestring_redirect']) -> list[herestring_redirect]: ...

class regex(Node):
    """kind 'regex'."""
    ...

class simple_expansion(Node):
    """kind 'simple_expansion'."""
    @overload
    def children(self, kind: Literal['special_variable_name']) -> list[special_variable_name]: ...
    @overload
    def children(self, kind: Literal['variable_name']) -> list[variable_name]: ...

class special_variable_name(Node):
    """kind 'special_variable_name'."""
    ...

class string(Node):
    """kind 'string'."""
    @overload
    def children(self, kind: Literal['arithmetic_expansion']) -> list[arithmetic_expansion]: ...
    @overload
    def children(self, kind: Literal['command_substitution']) -> list[command_substitution]: ...
    @overload
    def children(self, kind: Literal['expansion']) -> list[expansion]: ...
    @overload
    def children(self, kind: Literal['simple_expansion']) -> list[simple_expansion]: ...
    @overload
    def children(self, kind: Literal['string_content']) -> list[string_content]: ...

class string_content(Node):
    """kind 'string_content'."""
    ...

class subscript(Node):
    """kind 'subscript'."""
    def index(self) -> _primary_expression | binary_expression | compound_statement | concatenation | subshell | unary_expression | None: ...
    def name(self) -> variable_name | None: ...
    @overload
    def get(self, field: Literal['index']) -> _primary_expression | binary_expression | compound_statement | concatenation | subshell | unary_expression | None: ...
    @overload
    def get(self, field: Literal['name']) -> variable_name | None: ...

class subshell(Node):
    """kind 'subshell'."""
    def children(self, kind: Literal['_statement']) -> list[_statement]: ...

class ternary_expression(Node):
    """kind 'ternary_expression'."""
    def alternative(self) -> _expression | command_substitution | expansion | number | raw_string | simple_expansion | string | subscript | variable_name | None: ...
    def condition(self) -> _expression | command_substitution | expansion | number | raw_string | simple_expansion | string | subscript | variable_name | None: ...
    def consequence(self) -> _expression | command_substitution | expansion | number | raw_string | simple_expansion | string | subscript | variable_name | None: ...
    @overload
    def get(self, field: Literal['alternative']) -> _expression | command_substitution | expansion | number | raw_string | simple_expansion | string | subscript | variable_name | None: ...
    @overload
    def get(self, field: Literal['condition']) -> _expression | command_substitution | expansion | number | raw_string | simple_expansion | string | subscript | variable_name | None: ...
    @overload
    def get(self, field: Literal['consequence']) -> _expression | command_substitution | expansion | number | raw_string | simple_expansion | string | subscript | variable_name | None: ...

class test_command(Node):
    """kind 'test_command'."""
    @overload
    def children(self, kind: Literal['_expression']) -> list[_expression]: ...
    @overload
    def children(self, kind: Literal['redirected_statement']) -> list[redirected_statement]: ...

class test_operator(Node):
    """kind 'test_operator'."""
    ...

class translated_string(Node):
    """kind 'translated_string'."""
    def children(self, kind: Literal['string']) -> list[string]: ...

class unary_expression(Node):
    """kind 'unary_expression'."""
    def operator(self) -> Node | test_operator | None: ...
    def get(self, field: Literal['operator']) -> Node | test_operator | None: ...
    @overload
    def children(self, kind: Literal['_expression']) -> list[_expression]: ...
    @overload
    def children(self, kind: Literal['command_substitution']) -> list[command_substitution]: ...
    @overload
    def children(self, kind: Literal['expansion']) -> list[expansion]: ...
    @overload
    def children(self, kind: Literal['number']) -> list[number]: ...
    @overload
    def children(self, kind: Literal['raw_string']) -> list[raw_string]: ...
    @overload
    def children(self, kind: Literal['simple_expansion']) -> list[simple_expansion]: ...
    @overload
    def children(self, kind: Literal['string']) -> list[string]: ...
    @overload
    def children(self, kind: Literal['subscript']) -> list[subscript]: ...
    @overload
    def children(self, kind: Literal['variable_name']) -> list[variable_name]: ...

class unset_command(Node):
    """kind 'unset_command'."""
    @overload
    def children(self, kind: Literal['_primary_expression']) -> list[_primary_expression]: ...
    @overload
    def children(self, kind: Literal['concatenation']) -> list[concatenation]: ...
    @overload
    def children(self, kind: Literal['variable_name']) -> list[variable_name]: ...

class variable_assignment(Node):
    """kind 'variable_assignment'."""
    def name(self) -> subscript | variable_name | None: ...
    def value(self) -> _primary_expression | array | binary_expression | concatenation | parenthesized_expression | postfix_expression | unary_expression | variable_assignment | None: ...
    @overload
    def get(self, field: Literal['name']) -> subscript | variable_name | None: ...
    @overload
    def get(self, field: Literal['value']) -> _primary_expression | array | binary_expression | concatenation | parenthesized_expression | postfix_expression | unary_expression | variable_assignment | None: ...

class variable_assignments(Node):
    """kind 'variable_assignments'."""
    def children(self, kind: Literal['variable_assignment']) -> list[variable_assignment]: ...

class variable_name(Node):
    """kind 'variable_name'."""
    ...

class while_statement(Node):
    """kind 'while_statement'."""
    def body(self) -> do_group | None: ...
    def condition(self) -> list[Node | _statement]: ...
    @overload
    def get(self, field: Literal['body']) -> do_group | None: ...
    @overload
    def get(self, field: Literal['condition']) -> list[Node | _statement]: ...

class word(Node):
    """kind 'word'."""
    ...
