# Typed node accessors for nix — generated from the node-schema (tsquery.stubs).
from __future__ import annotations
from typing import Literal, overload

class Node:
    type: str
    ...

_expression = apply_expression | assert_expression | attrset_expression | binary_expression | float_expression | function_expression | has_attr_expression | hpath_expression | if_expression | indented_string_expression | integer_expression | let_attrset_expression | let_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | with_expression

class apply_expression(Node):
    """kind 'apply_expression'."""
    def argument(self) -> attrset_expression | float_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | uri_expression | variable_expression | None: ...
    def function(self) -> apply_expression | attrset_expression | float_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | uri_expression | variable_expression | None: ...
    @overload
    def get(self, field: Literal['argument']) -> attrset_expression | float_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | uri_expression | variable_expression | None: ...
    @overload
    def get(self, field: Literal['function']) -> apply_expression | attrset_expression | float_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | uri_expression | variable_expression | None: ...

class assert_expression(Node):
    """kind 'assert_expression'."""
    def body(self) -> apply_expression | assert_expression | attrset_expression | binary_expression | float_expression | function_expression | has_attr_expression | hpath_expression | if_expression | indented_string_expression | integer_expression | let_attrset_expression | let_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | with_expression | None: ...
    def condition(self) -> _expression | None: ...
    @overload
    def get(self, field: Literal['body']) -> apply_expression | assert_expression | attrset_expression | binary_expression | float_expression | function_expression | has_attr_expression | hpath_expression | if_expression | indented_string_expression | integer_expression | let_attrset_expression | let_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | with_expression | None: ...
    @overload
    def get(self, field: Literal['condition']) -> _expression | None: ...

class attrpath(Node):
    """kind 'attrpath'."""
    def attr(self) -> list[identifier | interpolation | string_expression]: ...
    def get(self, field: Literal['attr']) -> list[identifier | interpolation | string_expression]: ...

class attrset_expression(Node):
    """kind 'attrset_expression'."""
    def children(self, kind: Literal['binding_set']) -> list[binding_set]: ...

class binary_expression(Node):
    """kind 'binary_expression'."""
    def left(self) -> apply_expression | attrset_expression | binary_expression | float_expression | has_attr_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | None: ...
    def operator(self) -> Node | None: ...
    def right(self) -> apply_expression | attrset_expression | binary_expression | float_expression | has_attr_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | None: ...
    @overload
    def get(self, field: Literal['left']) -> apply_expression | attrset_expression | binary_expression | float_expression | has_attr_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | None: ...
    @overload
    def get(self, field: Literal['operator']) -> Node | None: ...
    @overload
    def get(self, field: Literal['right']) -> apply_expression | attrset_expression | binary_expression | float_expression | has_attr_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | None: ...

class binding(Node):
    """kind 'binding'."""
    def field_attrpath(self) -> attrpath | None: ...
    def expression(self) -> _expression | None: ...
    @overload
    def get(self, field: Literal['attrpath']) -> attrpath | None: ...
    @overload
    def get(self, field: Literal['expression']) -> _expression | None: ...

class binding_set(Node):
    """kind 'binding_set'."""
    def field_binding(self) -> list[binding | inherit | inherit_from]: ...
    def get(self, field: Literal['binding']) -> list[binding | inherit | inherit_from]: ...

class comment(Node):
    """kind 'comment'."""
    ...

class dollar_escape(Node):
    """kind 'dollar_escape'."""
    ...

class ellipses(Node):
    """kind 'ellipses'."""
    ...

class escape_sequence(Node):
    """kind 'escape_sequence'."""
    ...

class float_expression(Node):
    """kind 'float_expression'."""
    ...

class formal(Node):
    """kind 'formal'."""
    def default(self) -> _expression | None: ...
    def name(self) -> identifier | None: ...
    @overload
    def get(self, field: Literal['default']) -> _expression | None: ...
    @overload
    def get(self, field: Literal['name']) -> identifier | None: ...

class formals(Node):
    """kind 'formals'."""
    def field_ellipses(self) -> ellipses | None: ...
    def field_formal(self) -> list[formal]: ...
    @overload
    def get(self, field: Literal['ellipses']) -> ellipses | None: ...
    @overload
    def get(self, field: Literal['formal']) -> list[formal]: ...

class function_expression(Node):
    """kind 'function_expression'."""
    def body(self) -> apply_expression | assert_expression | attrset_expression | binary_expression | float_expression | function_expression | has_attr_expression | hpath_expression | if_expression | indented_string_expression | integer_expression | let_attrset_expression | let_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | with_expression | None: ...
    def field_formals(self) -> formals | None: ...
    def universal(self) -> identifier | None: ...
    @overload
    def get(self, field: Literal['body']) -> apply_expression | assert_expression | attrset_expression | binary_expression | float_expression | function_expression | has_attr_expression | hpath_expression | if_expression | indented_string_expression | integer_expression | let_attrset_expression | let_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | with_expression | None: ...
    @overload
    def get(self, field: Literal['formals']) -> formals | None: ...
    @overload
    def get(self, field: Literal['universal']) -> identifier | None: ...

class has_attr_expression(Node):
    """kind 'has_attr_expression'."""
    def field_attrpath(self) -> attrpath | None: ...
    def expression(self) -> apply_expression | attrset_expression | binary_expression | float_expression | has_attr_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | None: ...
    def operator(self) -> Node | None: ...
    @overload
    def get(self, field: Literal['attrpath']) -> attrpath | None: ...
    @overload
    def get(self, field: Literal['expression']) -> apply_expression | attrset_expression | binary_expression | float_expression | has_attr_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | None: ...
    @overload
    def get(self, field: Literal['operator']) -> Node | None: ...

class hpath_expression(Node):
    """kind 'hpath_expression'."""
    @overload
    def children(self, kind: Literal['interpolation']) -> list[interpolation]: ...
    @overload
    def children(self, kind: Literal['path_fragment']) -> list[path_fragment]: ...

class identifier(Node):
    """kind 'identifier'."""
    ...

class if_expression(Node):
    """kind 'if_expression'."""
    def alternative(self) -> _expression | None: ...
    def condition(self) -> _expression | None: ...
    def consequence(self) -> _expression | None: ...
    @overload
    def get(self, field: Literal['alternative']) -> _expression | None: ...
    @overload
    def get(self, field: Literal['condition']) -> _expression | None: ...
    @overload
    def get(self, field: Literal['consequence']) -> _expression | None: ...

class indented_string_expression(Node):
    """kind 'indented_string_expression'."""
    @overload
    def children(self, kind: Literal['dollar_escape']) -> list[dollar_escape]: ...
    @overload
    def children(self, kind: Literal['escape_sequence']) -> list[escape_sequence]: ...
    @overload
    def children(self, kind: Literal['interpolation']) -> list[interpolation]: ...
    @overload
    def children(self, kind: Literal['string_fragment']) -> list[string_fragment]: ...

class inherit(Node):
    """kind 'inherit'."""
    def attrs(self) -> inherited_attrs | None: ...
    def get(self, field: Literal['attrs']) -> inherited_attrs | None: ...

class inherit_from(Node):
    """kind 'inherit_from'."""
    def attrs(self) -> inherited_attrs | None: ...
    def expression(self) -> _expression | None: ...
    @overload
    def get(self, field: Literal['attrs']) -> inherited_attrs | None: ...
    @overload
    def get(self, field: Literal['expression']) -> _expression | None: ...

class inherited_attrs(Node):
    """kind 'inherited_attrs'."""
    def attr(self) -> list[identifier | interpolation | string_expression]: ...
    def get(self, field: Literal['attr']) -> list[identifier | interpolation | string_expression]: ...

class integer_expression(Node):
    """kind 'integer_expression'."""
    ...

class interpolation(Node):
    """kind 'interpolation'."""
    def expression(self) -> _expression | None: ...
    def get(self, field: Literal['expression']) -> _expression | None: ...

class let_attrset_expression(Node):
    """kind 'let_attrset_expression'."""
    def children(self, kind: Literal['binding_set']) -> list[binding_set]: ...

class let_expression(Node):
    """kind 'let_expression'."""
    def body(self) -> apply_expression | assert_expression | attrset_expression | binary_expression | float_expression | function_expression | has_attr_expression | hpath_expression | if_expression | indented_string_expression | integer_expression | let_attrset_expression | let_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | with_expression | None: ...
    def get(self, field: Literal['body']) -> apply_expression | assert_expression | attrset_expression | binary_expression | float_expression | function_expression | has_attr_expression | hpath_expression | if_expression | indented_string_expression | integer_expression | let_attrset_expression | let_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | with_expression | None: ...
    def children(self, kind: Literal['binding_set']) -> list[binding_set]: ...

class list_expression(Node):
    """kind 'list_expression'."""
    def element(self) -> list[attrset_expression | float_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | uri_expression | variable_expression]: ...
    def get(self, field: Literal['element']) -> list[attrset_expression | float_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | uri_expression | variable_expression]: ...

class parenthesized_expression(Node):
    """kind 'parenthesized_expression'."""
    def expression(self) -> _expression | None: ...
    def get(self, field: Literal['expression']) -> _expression | None: ...

class path_expression(Node):
    """kind 'path_expression'."""
    @overload
    def children(self, kind: Literal['interpolation']) -> list[interpolation]: ...
    @overload
    def children(self, kind: Literal['path_fragment']) -> list[path_fragment]: ...

class path_fragment(Node):
    """kind 'path_fragment'."""
    ...

class rec_attrset_expression(Node):
    """kind 'rec_attrset_expression'."""
    def children(self, kind: Literal['binding_set']) -> list[binding_set]: ...

class select_expression(Node):
    """kind 'select_expression'."""
    def field_attrpath(self) -> attrpath | None: ...
    def default(self) -> attrset_expression | float_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | uri_expression | variable_expression | None: ...
    def expression(self) -> attrset_expression | float_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | spath_expression | string_expression | uri_expression | variable_expression | None: ...
    @overload
    def get(self, field: Literal['attrpath']) -> attrpath | None: ...
    @overload
    def get(self, field: Literal['default']) -> attrset_expression | float_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | uri_expression | variable_expression | None: ...
    @overload
    def get(self, field: Literal['expression']) -> attrset_expression | float_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | spath_expression | string_expression | uri_expression | variable_expression | None: ...

class source_code(Node):
    """kind 'source_code'."""
    def expression(self) -> _expression | None: ...
    def get(self, field: Literal['expression']) -> _expression | None: ...

class spath_expression(Node):
    """kind 'spath_expression'."""
    ...

class string_expression(Node):
    """kind 'string_expression'."""
    @overload
    def children(self, kind: Literal['dollar_escape']) -> list[dollar_escape]: ...
    @overload
    def children(self, kind: Literal['escape_sequence']) -> list[escape_sequence]: ...
    @overload
    def children(self, kind: Literal['interpolation']) -> list[interpolation]: ...
    @overload
    def children(self, kind: Literal['string_fragment']) -> list[string_fragment]: ...

class string_fragment(Node):
    """kind 'string_fragment'."""
    ...

class unary_expression(Node):
    """kind 'unary_expression'."""
    def argument(self) -> apply_expression | attrset_expression | binary_expression | float_expression | has_attr_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | None: ...
    def operator(self) -> Node | None: ...
    @overload
    def get(self, field: Literal['argument']) -> apply_expression | attrset_expression | binary_expression | float_expression | has_attr_expression | hpath_expression | indented_string_expression | integer_expression | let_attrset_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | None: ...
    @overload
    def get(self, field: Literal['operator']) -> Node | None: ...

class uri_expression(Node):
    """kind 'uri_expression'."""
    ...

class variable_expression(Node):
    """kind 'variable_expression'."""
    def name(self) -> identifier | None: ...
    def get(self, field: Literal['name']) -> identifier | None: ...

class with_expression(Node):
    """kind 'with_expression'."""
    def body(self) -> apply_expression | assert_expression | attrset_expression | binary_expression | float_expression | function_expression | has_attr_expression | hpath_expression | if_expression | indented_string_expression | integer_expression | let_attrset_expression | let_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | with_expression | None: ...
    def environment(self) -> _expression | None: ...
    @overload
    def get(self, field: Literal['body']) -> apply_expression | assert_expression | attrset_expression | binary_expression | float_expression | function_expression | has_attr_expression | hpath_expression | if_expression | indented_string_expression | integer_expression | let_attrset_expression | let_expression | list_expression | parenthesized_expression | path_expression | rec_attrset_expression | select_expression | spath_expression | string_expression | unary_expression | uri_expression | variable_expression | with_expression | None: ...
    @overload
    def get(self, field: Literal['environment']) -> _expression | None: ...
